### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by AndrewSB**
This doesn't work perfectly - it looks like the Automation target has an error when running `swift build`. 

It works for the SwipeTransition framework though, and has made it so I can target my branch as a dependency in my app. I might look to fix this in a few weeks, but if someone else would like to commandeer this and finish what I started, please feel free!

### CODE REVIEW

**Comment by tattn** [comment]
Thank you for your contribution!
It's a nice feature 👍 

I'll merge it after trying it.

**Comment by tattn** [comment]
@AndrewSB  it may be broken with Carthage build.
```bash
% carthage update
*** Checking out SwipeTransition at "0452b7929e128631e856dce2db0780422bacd008"
*** xcodebuild output can be found in /var/folders/z3/lyh75tws0hg4nsp2wrg6gxnw0000gq/T/carthage-xcodebuild.cv7MVo.log
*** Building scheme "SwipeTransition" in SwipeTransition.xcodeproj
Build Failed
        Task failed with exit code 65:
```

Could you fix the problem?

**Comment by AndrewSB** [comment]
just rebased all the changes on master.

2 issues with this PR:

1. breaks Carthage support. this isn't something i'm going to prioritize fixing, i'm happy to continue using my branch
2. It has a single "Automation" product that isn't exposed, instead of having AutoSwipeBack and AutoSwipeToDismiss as 2 targets that can be pulled in. since I'm only using the SwipeBack framework, i haven't taken the time to separate them out

I'm happy to accept anyone else's work on top of this to enable that, i'll try to keep my branch upto date 😄

**Comment by karthikAdaptavant** [comment]
Hi @tattn Any update on the above PR ? are you merging it 
we would like to have spm version

**Comment by tattn** [comment]
Sorry for my late reply.

I think this implementation is good and I now believe that Carthage support is unnecessary.

Therefore, I'd like to merge this PR, but I can't merge it into main branch until updating README.md and some code.

So I create swiftpm branch and I'll merge this PR into it after resolving conflicts.
I'd like to fix it if I have time, but would welcome PRs from anyone.

**Comment by hansemannn** [comment]
@tattn Any update here? It would be great to have SPM support :)

**Comment by tattn** [comment]
I will merge this PR into `swiftpm` branch, so if you are in a hurry, please use the `swiftpm` branch. I plan to release it after making some adjustments to the implementation.

**Comment by AndrewSB** [comment]
@hansemannn i've been using `.package(url: "https://github.com/reclipapp/SwipeTransition", revision: "222f5246f128ab459a20aef06935e6ef29240e51")` for about a year now, we'll keep it upto date until upstream is fully SPM compliant

**Pull request merged**
